### ISSUE TITLE
"home" tab / chords

### ISSUE THREAD

**Issue by hankstue** [mattypiper/umtabs#19]
seeking guitar tabs / chords for the song "Home" off of the Bottom Half album. Please reach out if you can provide any help!

**Comment by rmsgb** [comment]
Here's a start for at least strumming along:
[Home tab.txt](https://github.com/mattypiper/umtabs/files/2564765/Home.tab.txt)

Let me know if you have questions or if you figure out any more. 
If I can figure out more I'll post. 

-Mike

**Comment by mattypiper** [comment]
Closed in 84bff5
